
/********************************************/
** 	the Treat-PRYSM project 				**
** 	by Sage Wyatt and Shahab Abtahi 		**
** 	October 2025 - September 2026 			**
**	Drug - Tamsulosin						**
**											**
**	File 2.1: Exposure Generation for BPH	**
/********************************************/;


/**************************************************************************/
/* Set up library references and global options                           */
/**************************************************************************/

libname rawdata "F:\Users\Wyatt003\BPH_nephrolithiasis\SAS";
libname output "F:\Users\Wyatt003\BPH_nephrolithiasis\Output";
libname codelist "C:\Users\Wyatt003\OneDrive - Universiteit Utrecht\Documents\Codelists\3_MagdasCodes";

options fullstimer; /* Display detailed resource usage info in log */


/**************************************************************************/
* Combining 4 drug issue files into one big drug issue files
	NOTE: 
	* The script for creation of bph_drugs_fixed can be found in FixingCodelists, original SAS file generated by Magda
	* mg_dose had to be created by hand, upon consultation with Jos;                                  */
/**************************************************************************/;


Data drug_1 ;
Set rawdata.drugissue_1 (keep=patid issuedate prodcodeid dosageid quantity duration);
run;

Data drug_2 ;
Set rawdata.drugissue_2 (keep=patid issuedate prodcodeid dosageid quantity duration);
run;

Data drug_3 ;
Set rawdata.drugissue_3 (keep=patid issuedate prodcodeid dosageid quantity duration);
run;

Data drug_4 ;
Set rawdata.drugissue_4 (keep=patid issuedate prodcodeid dosageid quantity duration);
run;

* The data set OUTPUT.DRUG has 642563242 observation;

data output.drug;
	set drug_1
	drug_2
	drug_3
	drug_4;
run;





************************************** BPH COHORT ****************************************;

/**************************************************************************/
* Step 1: Extract BPH drug records;
/**************************************************************************/

	proc sql;
	CREATE TABLE output.bph_drugs AS
	SELECT med.patid, 
		   med.issuedate, 
		   med.dosageid, 
		   med.quantity,
		   med.duration,
		   bphcod.exposure,
		   bphcod.drugsubstancename,
		   bphcod.ProdCodeId,
		   bphcod.mg_dose
	FROM 
		rawdata.drugissue_1 AS med /*Change to include all 4 files */
	INNER JOIN
		codelist.bph_drugs_fixed AS bphcod
		ON med.ProdCodeId = bphcod.ProdCodeId
	WHERE med.quantity > 0;
quit;


/**************************************************************************/
/* STEP 2: Join with base_cohort so only patients in our main cohort remain.*/
/**************************************************************************/


PROC SQL;
CREATE TABLE bph_tam AS
	SELECT T.patid, 
T.issuedate, 
T.exposure, 
T.drugsubstancename, 
T.dosageid, 
T.quantity,
T.duration, 
T.mg_dose,
BC.regstartdate
	FROM output.bph_drugs AS T
	INNER JOIN output.bph_cohort AS BC ON BC.patid = T.patid
	WHERE T.quantity > 0
ORDER BY T.patid, T.issuedate; 
quit;

proc SQL;
SELECT COUNT(distinct patid) as n
FROM bph_tam;
quit;

/**************************************************************************/
/* STEP 3: Add daily dosage information                                  */
/**************************************************************************/
        
/* 1) Calculate 'treatment_duration' = quantity / daily_dose.             */
/* 2) 'mean_daily_dose' = mg_value * daily_dose (dose strength * freq).   */
/*			NOTE: There is only one prescribe mg value of tamsulosin in   */
/*			CPRD Aurum, 400mg dosages are then written as capsules in 	  */
/*			common dosages												  */
/* 3) We assume missing values correspond to 							  
	  1 pill a day (based on empirical observation, and that 0 pills a day
	  correspond to as needed, and set to 0.5 a day                       */;

proc sql;
	create table bph_tam_dose as
	select * ,
		   quantity / CASE 
						WHEN quantity IS NULL THEN 1 
						WHEN quantity = 0 THEN 0.5 
						ELSE quantity 
					END AS treatment_duration,
		   mg_dose * CASE 
							WHEN daily_dose IS NULL THEN 1 
							WHEN daily_dose = 0 THEN 0.5 
							ELSE daily_dose 
						END AS mean_daily_dose
	from bph_tam_dose
	ORDER BY patid, issuedate;
quit;

proc contents data = bph_tam_dose;
run;

/**************************************************************************/
/* Quick check: Count unique patients                                     */
/**************************************************************************/
title "Numbers of unique ids in bph cohort";
proc sql;
  select count(distinct patid) as n_patid
  from bph_tam_dose;
quit;

/* Check that there are no negative or zero durations */
title "Numbers of people with 0 treatment duration";
proc sql;
  select count(*) as n_zero_treat
  from bph_tam_dose
  where treatment_duration <= 0;
quit;


/* Check the distribution of mean_daily_dose to see if it is plausible (no extremely large or negative values) */
/* Some extreme values (e.g. 5000). Need to correct for this later */
/* max is 30 */
title "Max mean_daily_dose";
proc sql;
  select max(mean_daily_dose)
  from bph_tam_dose;
quit;


/**************************************************************************/
/* STEP 4: Exclude 'PrevalentUsers'                               */
/**************************************************************************/
/* 'Prevalent users' are those who had a drug prescription X years before   */
/* their baseline date. We identify them by comparing eventdate with the  */
/* baseline_dt in base_cohort. */

%let years = 1; /* Define the number of years for look-back */

* around 50 thousand prevalent users;

proc sql;
	create table PrevalentUsers as
	select distinct d1.patid
	from output.bph_cohort d1
		inner join bph_tam_dose d2
		on d1.patid = d2.patid
	where d2.issuedate between intnx('year', d1.baseline_dt, -&years) and d1.baseline_dt - 1;
quit;



/* We remove those in PrevalentUsers.                                 */
/* We only keep prescriptions dated on or after baseline.             */

proc sql;
	create table output.Rx_PostStart as
	select d1.*,
		   d2.issuedate,
		   d2.treatment_duration,
		   d2.mean_daily_dose,
		   d2.exposure,
		   d2.quantity
	from output.bph_cohort d1
		inner join bph_tam_dose d2
		on d1.patid = d2.patid
	where not exists (
		select 1
		from PrevalentUsers p
		where p.patid = d1.patid
		)
	and d2.issuedate >= d1.baseline_dt
	;
quit;
* replaced varaible d2.exposure with dr.prodcodeid, not sure if that is important;
/* Check how many unique patients remain after exclusion of prevalent. */
/* 185, 936 patients */
title "Numbers of unique ids after excluding prevalent users";
proc sql;
  select count(distinct patid) as n_patid
  from output.Rx_PostStart;
quit;

/**************************************************************************/
/* STEP 5: Identify earliest prescription date for each patient           */
/**************************************************************************/
/* Finds the minimum (earliest) eventdate among the valid prescriptions.  */

proc sql;
	create table output.BphEarliestDate as
	select patid,
		   min(issuedate) as earliest_rx_date format = ddmmyy10.
	from output.Rx_PostStart
	group by patid;
quit;


/* 1) We only keep rows where eventdate = earliest_rx_date.               */
/* 2) We call this 'EarliestRxAll'.                                       */
/* 3) If multiple rows share the same earliest date for a patient, we     */
/*    handle that in the subsequent step.                                 */
proc sql;
	create table output.EarliestRxBphAll as
	select p.patid,
		   p.exposure,
		   p.issuedate,
		   p.treatment_duration,
		   e.earliest_rx_date,
		   p.regstartdate
	from output.Rx_PostStart as p
		inner join output.BphEarliestDate as e
		on p.patid = e.patid
	where p.issuedate = e.earliest_rx_date;
quit;

/**************************************************************************/
/* STEP 6: Exclude patients who have more than one record on earliest Rx  */
/**************************************************************************/
/* If a patient has > 1 row on the earliest date (possibly multiple drugs),*/
/* we remove them so each patient has exactly one earliest Rx.            */
proc sql;
	create table ExcludeMulti as
	select patid
	from output.EarliestRxBphAll
	group by patid
	having count(distinct exposure) > 1  /* More than 1 unique exposure => Exclude */
	;
quit;

/* Check for ties in earliest date */
proc sql;
  select count(distinct patid) as n_excluded
  from ExcludeMulti;
quit;

proc sql;
	create table EarliestRxBph_Filtered as
	select *
	from output.EarliestRxBphAll
	where patid not in (select patid from output.ExcludeMulti);
quit;

proc sql;
	create table EarliestRxBph_Filtered as
	select distinct
	       patid, 
		   exposure, 
		   earliest_rx_date, 
		   treatment_duration,
		   regstartdate
	from EarliestRxBph_Filtered
	group by patid, exposure
	having treatment_duration = max(treatment_duration)  /* Prefer longest treatment if two prescriptions on same date */
	;
quit;

/**************************************************************************/
/* STEP 7: Exclude if Follow-up period is less than 365 days  */
/**************************************************************************/

PROC SQL;
create table EarliestRx_washout AS
select * 
from EarliestRxBph_Filtered
having earliest_rx_date - regstartdate > 365;
quit;

/**************************************************************************/
/* STEP 8: Exclude if subarachnoid hemorrhage (aSAH) occurred before Rx  */
/**************************************************************************/

/* If a patient s first aSAH date (HOSP ONLY) is before earliest Rx, we drop them.    */
/* NOTE: DO NOT RUN UNTIL HES APC LINKAGE */
/* NOTE: Jos's version requires both hospital and gp data so I have written new script myself for the timebeing*/

proc sql;
CREATE TABLE EarliestRx_aSah_Exclusion AS
SELECT d1.* , d2.patid, d2.aSAH_gp_dt
FROM EarliestRx_washout as d1
INNER JOIN output.bph_cohort as d2 
ON d1.patid = d2.patid
	WHERE d2.aSAH_gp_dt > earliest_rx_date or d2.aSAH_gp_dt is NULL;
quit;


/**************************************************************************/
/* STEP 9: Keep only the same drug as earliest for final prescription set */
/**************************************************************************/
/* 1) We bring back all prescriptions from Rx_PostStart that match the    */
/*    same exposure name and occur after earliest Rx date for that patid. */
/* 2) This will be used for bridging (continuous coverage) analysis.      */

proc sql;
	create table output.BphIndexDrug as
	select p.*
	from output.Rx_PostStart p
		inner join EarliestRx_aSah_Exclusion e
		on p.patid = e.patid
	where p.exposure = e.exposure
	  and p.bph_dt >= e.earliest_rx_date
	order by p.patid, p.bph_dt;
quit;



************************************** NEPHROLITHIASIS COHORT ****************************************;




/**************************************************************************/
* Step 1: Extract NL drug records;
/**************************************************************************/




	proc sql;
	CREATE TABLE nl_drugs_magda AS
	SELECT med.patid, 
		   med.issuedate, 
		   med.dosageid, 
		   nlcod.exposure,
		   nlcod.drugsubstancename,
		   nlcod.ProdCodeId,
		   nlcod.quantity,
		   nlcod.mg_dose
	FROM 
		output.drug AS med
	INNER JOIN
		codelist.bph_drugs_fixed AS nlcod
		ON med.ProdCodeId = nlcod.ProdCodeId
	WHERE nlcod.quantity > 0 and nlcod.drugsubstancename = "Tamsulosin";
quit;


/**************************************************************************/
/* STEP 2: Join with base_cohort so only patients in our main cohort remain.*/
/**************************************************************************/


PROC SQL;
CREATE TABLE nl_tam AS
	SELECT T.patid, 
T.issuedate, 
T.exposure, 
T.drugsubstancename, 
T.dosageid, 
T.quantity, 
T.mg_dose,
BC.regstartdate
	FROM nl_drugs_magda AS T
	INNER JOIN output.nl_cohort AS BC ON BC.patid = T.patid
	WHERE T.quantity > 0
	GROUP BY BC.patid
ORDER BY T.patid, T.issuedate; 
quit;

proc SQL;
SELECT COUNT(distinct patid) as n
FROM nl_tam;
quit;

/**************************************************************************/
/* STEP 3: Add daily dosage information                                  */
/**************************************************************************/
/* 1) Left-join with common_dosages to retrieve typical daily dose.       */          
/* 2) Calculate 'treatment_duration' = quantity / daily_dose.             */
/* 3) 'mean_daily_dose' = mg_value * daily_dose (dose strength * freq).   */
/*			NOTE: There is only one prescribe mg value of tamsulosin in   */
/*			CPRD Aurum, 400mg dosages are then written as capsules in 	  */
/*			common dosages												  */
/* 4) We assume missing values correspond to 							  
	  1 pill a day (based on empirical observation, and that 0 pills a day
	  correspond to as needed, and set to 0.5 a day                       */;

*NOTE: I am concerned about the number of missing dosageids here. Original script was inner join, but lost 10 million records, changed to left outer join*;

PROC SQL;
CREATE TABLE nl_tam_dose AS
	SELECT *
	FROM nl_tam AS B
	LEFT OUTER JOIN codelist.common_dosages AS CD ON B.dosageid = CD.dosageid
ORDER BY dosageid; 
quit;


proc sql;
	create table nl_tam_dose as
	select * ,
		   quantity / CASE 
						WHEN daily_dose IS NULL THEN 1 
						WHEN daily_dose = 0 THEN 0.5 
						ELSE daily_dose 
					END AS treatment_duration,
		   mg_dose * CASE 
							WHEN daily_dose IS NULL THEN 1 
							WHEN daily_dose = 0 THEN 0.5 
							ELSE daily_dose 
						END AS mean_daily_dose
	from nl_tam_dose
	ORDER BY patid, issuedate;
quit;

proc contents data = bph_tam_dose;
run;

/**************************************************************************/
/* STEP 4: Exclude 'PrevalentUsers'                               */
/**************************************************************************/
/* 'Prevalent users' are those who had a drug prescription X years before   */
/* their baseline date. We identify them by comparing eventdate with the  */
/* baseline_dt in base_cohort. */

%let years = 1; /* Define the number of years for look-back */

proc sql;
	create table PrevalentUsers as
	select distinct d1.patid
	from output.nl_cohort d1
		inner join nl_tam_dose d2
		on d1.patid = d2.patid
	where d2.issuedate between intnx('year', d1.baseline_dt, -&years) and d1.baseline_dt - 1;
quit;



/* We remove those in PrevalentUsers.                                 */
/* We only keep prescriptions dated on or after baseline.             */
proc sql;
	create table Rx_PostStart as
	select d1.*,
		   d2.issuedate,
		   d2.treatment_duration,
		   d2.mean_daily_dose,
		   d2.exposure,
	from output.nl_cohort d1
		inner join nl_tam_dose d2
		on d1.patid = d2.patid
	where not exists (
		select 1
		from PrevalentUsers p
		where p.patid = d1.patid
		)
	and d2.issuedate >= d1.baseline_dt
	;
quit;
* replaced varaible d2.exposure with dr.prodcodeid, not sure if that is important;
/* Check how many unique patients remain after exclusion of prevalent. */
/* 185, 936 patients */
title "Numbers of unique ids after excluding prevalent users";
proc sql;
  select count(distinct patid) as n_patid
  from Rx_PostStart;
quit;

/**************************************************************************/
/* STEP 5: Identify earliest prescription date for each patient           */
/**************************************************************************/
/* Finds the minimum (earliest) eventdate among the valid prescriptions.  */
/* NOTE: THIS IS DEFINED AS CLINICAL EVENT DATE NOT PRESCRIPTION DATE
PRESCRIPTION DATE NOT RELEVANT FOR NL BECAUSE COMPARATOR ARM MAY NOT TAKE TREATMENT */

proc sql;
	create table nlEarliestDate as
	select patid,
		   min(nl_dt) as earliest_rx_date format = ddmmyy10.
	from output.Rx_PostStart
	group by patid;
quit;


/**************************************************************************/
/* STEP 7: Exclude if Follow-up period is less than 365 days  */
/**************************************************************************/

PROC SQL;
create table output.nl_tam_filter AS
select * 
from nlEarliestDate
having earliest_rx_date - regstartdate > 365;
quit;

/**************************************************************************/
/* STEP 8: Exclude if subarachnoid hemorrhage (aSAH) occurred before Rx  */
/**************************************************************************/

/* If a patient s first aSAH date (HOSP ONLY) is before earliest Rx, we drop them.    */
/* NOTE: DO NOT RUN UNTIL HES APC LINKAGE */
/* NOTE: Jos's version requires both hospital and gp data so I have written new script myself for the timebeing*/

proc sql;
CREATE TABLE EarliestRx_aSah_Exclusion AS
SELECT d1.* , d2.patid, d2.aSAH_gp_dt
FROM output.EarliestRx_SingleDrug as d1
INNER JOIN output.bph_cohort as d2 
ON d1.patid = d2.patid
	WHERE d2.aSAH_gp_dt > earliest_rx_date or d2.aSAH_gp_dt is NULL;
quit;


/**************************************************************************/
/* STEP 9: Keep only the same drug as earliest for final prescription set*/
/**************************************************************************/
/* 1) We bring back all prescriptions from Rx_PostStart that match the    */
/*    same exposure name and occur after earliest Rx date for that patid. */
/* 2) This will be used for bridging (continuous coverage) analysis.      */
proc sql;
	create table output.NlIndexDrug as
	select p.*
	from output.Rx_PostStart p
		inner join EarliestRx_aSah_Exclusion e
		on p.patid = e.patid
	where p.exposure = e.exposure
	  and p.eventdate >= e.earliest_rx_date
	order by p.patid, p.eventdate;
quit;
